### ISSUE TITLE
Examples fail when popular_products table is distributed

### ISSUE THREAD

**Issue by serprex** [citusdata/postgresql-topn#32]
```
postgres=# SELECT (topn(topn_union_agg(agg_data), 10)).*
postgres-# FROM popular_products
postgres-# WHERE review_date >= '2000-01-01' AND review_date < '2000-02-01'
postgres-# ORDER BY 2 DESC;
    item    | frequency
------------+-----------
 0375404368 |       217
 0345417623 |       217
 0375404376 |       217
 0375408738 |       217
 043936213X |       204
 0939173344 |       204
 0590353403 |       204
 0807286001 |       204
 0807281956 |       204
 0807281751 |       204
(10 rows)

postgres=# SELECT (topn(topn_union_agg(agg_data), 10)).*
FROM popular_products_distributed
WHERE review_date >= '2000-01-01' AND review_date < '2000-02-01'
ORDER BY 2 DESC;
ERROR:  set-valued function called in context that cannot accept a set
LINE 1: SELECT (topn(topn_union_agg(agg_data), 10)).*
        ^
```
Similar issue for the example after this one too

**Comment by metdos** [comment]
@serprex, is this a regression in 8.2? Could you also test this with 8.2 and check if it works there?

**Comment by serprex** [comment]
No. Tested that it also doesn't work in `8.2` or `8.0`

**Comment by furkansahin** [comment]
This is actually a known bug on the Citus side https://github.com/citusdata/citus/issues/2265. We have regression tests in Citus repo for this case https://github.com/citusdata/citus/blob/fd3b0044b4f09ae9e4225ddba7dec8ad2c5e5932/src/test/regress/sql/custom_aggregate_support.sql#L225. As it is stated in the regression test file, this query will be supported once the issue in Citus is fixed.
