### ISSUE TITLE
Build failure against PostgreSQL 13

### ISSUE THREAD

**Issue by devrimgunduz** [citusdata/postgresql-topn#42]
Hi,

topn fails to build against PostgreSQL 13. 13.0 is due tomorrow. Can you please take a look? Thanks!

topn.c:30:10: fatal error: utils/jsonapi.h: No such file or directory
   30 | #include "utils/jsonapi.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: topn.o] Error 1
make[1]: *** Waiting for unfinished jobs....
topn.c:30:10: fatal error: 'utils/jsonapi.h' file not found
#include "utils/jsonapi.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [/usr/pgsql-13/lib/pgxs/src/makefiles/../../src/Makefile.global:1051: topn.bc] Error 1

**Comment by devrimgunduz** [comment]
Hi,

What is the timeline for a new release?

Regards, Devrim

**Comment by devrimgunduz-edb** [comment]
ping

**Comment by serprex** [comment]
ping @metdos

**Comment by hanefi** [comment]
@devrimgunduz we tagged 2.3.1 today. We created the packages on our repos, so it should be fine on PGDG as well

**Comment by devrimgunduz** [comment]
@hanefi Thanks! I pushed packages on the same day, but forgot to update this issue. Sorry about that.

Regards, Devrim
